pages:
  stage: deploy
  image: python:latest
  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - /var/cache/apt/archives
      - /root/.cache/pip
      - /usr/local/lib/python3.*/site-packages
  before_script:
    - apt-get update -y
    - apt-get install -y libcairo2-dev libfreetype6-dev libffi-dev libjpeg-dev libpng-dev libz-dev
    - pip install --upgrade pip
    - pip install --user -r requirements.txt
    - export PATH="$PATH:$(python -m site --user-base)/bin"
  script:
    - mkdocs build --site-dir public
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      changes:
        - docs/*
        - mkdocs.yml
