name: deploy-website 
on:
  push:
    branches:
      - main
    paths:
      - 'docs/**' # Watch for changes in the docs folder
      - 'mkdocs.yml' # Watch for changes in the mkdocs.yml file
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
            fetch-depth: 0
            sparse-checkout: |
              docs
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v2.1.8
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: sudo apt-get install libcairo2-dev libfreetype6-dev libffi-dev libjpeg-dev libpng-dev libz-dev
      - run: sudo apt-get install pngquant
      - run: pip install --upgrade pip && pip install --user -r requirements.txt
      - run: mkdocs gh-deploy --force
